### ISSUE TITLE
Content of `Verifier.toml` is not valid

### ISSUE THREAD

**Issue by qdrn** [AztecProtocol/docs#18]
Using the provided values:
```
y = "4"
setpub = []
```
it returns:
```
root@1ff1697833b8:~/circuits# nargo verify my_proof
thread 'main' panicked at 'Expected 1 number of values in Verifier.toml, but got 2 number of values', crates/nargo/src/cli/verify_cmd.rs:83:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
I believe it should be the following:
```
y = "4"
```

**Comment by Globallager** [comment]
Thanks for creating the issue.

The detailed guide on [the Noir page](https://docs.aztec.network/developers/noir) has been depreciated in the favor of maintaining one single source of truth in [the Noir book](https://noir-lang.github.io/book/). This issue was addressed correspondingly in https://github.com/noir-lang/book/pull/22/.
